# @package _global_

stages:
  - name: train-single
    overrides:
      - +exp=train-single
    load_checkpoint_from_previous: false
  - name: finetune-single
    overrides:
      - +exp=finetune-single
      - +task/patches=[no_xy_term,look_ahead_xy]
    load_checkpoint_from_previous: true
