# @package _global_

defaults:
  - /algo/sac/module: large
  - override /algo: sac

total_iters: 10000
checkpoint_interval: 2000
upload_interval: 2000

algo:
  gamma: 0.94
  buffer_size: 512
  buffer_device: "cuda"
  use_correlated: false
  actor_loc_reg_scale: 16.0
  actor_loc_reg_power: 4.0
  critic_batch_size: 4096
  actor_batch_size: 4096

task:
  num_envs: 2048

  reward:
    loco:
      action_rate_l2:
        weight: 0.01
