[project]
name = "aa-mjlab-env"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "active_adaptation[mjlab]",
    "hdmi",
]

[tool.uv.sources]
active_adaptation = { path = "../..", editable = true }
hdmi = { path = "../../projects/hdmi", editable = true }

[tool.uv]
package = false
